Adds Instagram Account Information, Ad Interests, Login Activity, Reels & More [JSON] (CU-2n01fcr)
open-data-labs/userdata-extractor pull request #7
Opened 2022-07-15 18:13 UTC by josephcsoti

### Description

Adds JSON extractors for some needed data for the [helloworld.vana.xyz ](https://helloworld.vana.xyz/) app & some more curious areas of interest 

### Now supported
```
account_information.json    ✅
personal_information.json   ✅
profile_changes.json        ✅
advertisers_using_....json  ✅
account_based_in.json       ✅
ads_interests.json          ✅
login_activity.json         ✅
logout_activity.json        ✅
your_reels_sentiments.json  ✅
your_reels_topics.json      ✅
```

### Current Progress (also in readme)
```
.
├── account_information
│   ├── account_information.json      ✅
│   ├── personal_information.json     ✅
│   ├── professional_information.json ❌ (no data example)
│   └── profile_changes.json          ✅
├── ads_and_businesses
│   └── advertisers_using_your_activity_or_information.json  ✅
├── ads_and_topics
│   ├── accounts_you're_not_interested_in.json
│   ├── ads_clicked.json
│   ├── ads_viewed.json
│   ├── posts_viewed.json
│   └── videos_watched.json
├── apps_and_websites
│   └── active_apps.json
├── autofill_information
│   └── no-data.txt
├── avatars_store
│   └── no-data.txt
├── blockchain_accounts
│   └── no-data.txt
├── comments
│   └── post_comments.json
├── comments_settings
│   ├── comments_allowed_from.json
│   └── use_cross-app_messaging.json
├── contacts
│   └── synced_contacts.json
├── content
│   ├── posts_1.json
│   ├── profile_photos.json
│   └── stories.json
├── device_information
│   ├── camera_information.json
│   └── devices.json
├── events
│   └── no-data.txt
├── followers_and_following
│   ├── blocked_accounts.json
│   ├── followers.json
│   ├── following.json
│   ├── pending_follow_requests.json
│   ├── recent_follow_requests.json
│   └── recently_unfollowed_accounts.json
├── fundraisers
│   └── no-data.txt
├── guides
│   └── no-data.txt
├── information_about_you
│   ├── account_based_in.json ✅
│   └── ads_interests.json    ✅
├── likes
│   ├── liked_comments.json
│   └── liked_posts.json
├── login_and_account_creation
│   ├── login_activity.json   ✅
│   ├── logout_activity.json  ✅
│   ├── password_change_activity.json
│   └── signup_information.json
├── loyalty_accounts
│   └── no-data.txt
├── media ❌ (skipping non-text formats)
├── messages
│   ├── inbox
│   │   ├── instagram-username_u2df5hj
│   │   │   ├── message_1.json
│   │   │   └── photos
│   │   │       ├── pic1.jpg
│   │   │       └── pic2.jpg
│   │   │   └── videos
│   │   │       └── video.mp4
│   ├── message_requests
│   │   ├── instagramuser_fpaxg_gl0a
│   │   │   └── message_1.json
│   ├── secret_conversations.json
│   └── secret_groups.json
├── monetization
│   └── eligibility.json
├── past_instagram_insights
│   └── no-data.txt
├── recent_searches
│   └── account_searches.json
├── reports
│   └── no-data.txt
├── saved
│   └── saved_posts.json
├── shopping
│   └── recently_viewed_items.json
├── story_sticker_interactions
│   ├── emoji_sliders.json
│   ├── polls.json
│   ├── questions.json
│   └── quizzes.json
└── your_topics
    ├── your_reels_sentiments.json  ✅
    └── your_reels_topics.json      ✅
```

### Other changes

_none_

### Tested

Added ~11 tests :tada:

```
 PASS  test/extractor/instagram/json/loginActivityJson.test.ts
 PASS  test/extractor/instagram/json/yourReelsTopicsJson.test.ts
 PASS  test/extractor/instagram/json/accountInformationJson.test.ts
 PASS  test/extractor/instagram/json/profileChangesJson.test.ts
 PASS  test/extractor/instagram/json/adsInterestsJson.test.ts
 PASS  test/extractor/instagram/json/logoutActivityJson.test.ts
 PASS  test/extractor/instagram/json/advertisersUsingYourActivityOrInformationJson.test.ts
 PASS  test/extractor/instagram/json/professionalInformationJson.test.ts
 PASS  test/extractor/instagram/json/personalInformationJson.test.ts
 PASS  test/extractor/instagram/json/yourReelsSentimentsJson.test.ts
 PASS  test/extractor/instagram/json/accountBasedInJson.test.ts
 ```

### Related issues

_no related issues_

### Backwards compatibility

_we are starting from ground zero so every addition is a good breaking change_

### Keeping up with the ✨ integrations ✨ 
![instagram](https://user-images.githubusercontent.com/15241644/179327096-c58e0115-23e5-4782-8bd0-2c501fc7f429.gif)

### An absolute B O P to listen to as you review
[![Sky Ferreira - Everything is Embarrassing](https://user-images.githubusercontent.com/15241644/179327722-d43c2fdd-07c3-428c-bec1-0353b724c9c5.png)](https://open.spotify.com/track/70v5mCvyPRquTyU7qTIU81?si=e288f52b8f754690)

2022-07-17 21:04 UTC, Kahtaf requested changes
Really amazing work @josephcsoti! Had a few minor requests, especially about the `.js`  extension in the imports.

2022-07-17 21:04 UTC, Kahtaf commented on src/database/sqliteDatabase.ts
> +          columnNameType.push(`${columnName} text`);
If we make the default `text`, we need to add case statements for `integer` and `date`, otherwise those types will be considered text too.

2022-07-17 21:04 UTC, Kahtaf commented on src/extractor/fileExtractor.ts
> +import { Database } from "../database/database";
All local imports will need the `.js` extension, otherwise we get an error when calling this package from `corasli-gui` (unless you have fixed this).

2022-07-17 21:04 UTC, Kahtaf commented on src/extractor/index.ts
> +import * as Instagram from "./instagram";
We should be careful about removing the `.js` extension, I was having a lot of issues without it when calling this package from `corsali-gui`. Let's sync up on how to publish a beta version of this package so you can do some testing to see if the `.js` extension is not required.

2022-07-17 21:04 UTC, Kahtaf commented on src/extractor/instagram/json/loginActivityJson.ts
> +          acc[columnName] = (v && v.value !== "" ? v.value : v.timestamp) ?? "";
Can we simplify to: `acc[columnName] = v?.value || v?.timestamp;`?

2022-07-17 21:04 UTC, Kahtaf commented on src/extractor/instagram/json/logoutActivityJson.ts
> +          acc[columnName] = (v && v.value !== "" ? v.value : v.timestamp) ?? "";
Same here: `acc[columnName] = v?.value || v?.timestamp;`

2022-07-17 21:04 UTC, Kahtaf commented on src/extractor/instagram/json/personalInformationJson.ts
> +      profile_photo: mediaData.uri,
Something to think about here: all image URIs are pointing to a local file path, which we're not keeping. Not sure if it's worth storing these URIs if the file it points to is not accessible.

2022-07-17 21:04 UTC, Kahtaf commented on src/extractor/instagram/models/accountInformation.ts
> +   * Exists: JSON
What's the purpose of this `Exists: JSON` comment? Are we saying it only exists in the JSON version of the extract?

2022-07-17 21:04 UTC, Kahtaf commented on src/extractor/jsonExtractor.ts
> +  async loadJson(json: object) {
Can we change this to a public setter instead? Based on the functionality, that's what it seems to be doing.

2022-07-19 17:09 UTC, josephcsoti commented on src/extractor/instagram/models/accountInformation.ts
> +   * Exists: JSON
Yes! It's meant to keep track if a field exists in on or the other :) I only checked JSON so far but will update if HTML has it as well

2022-07-19 17:09 UTC, josephcsoti commented on src/extractor/instagram/json/personalInformationJson.ts
> +      profile_photo: mediaData.uri,
Hmmm I thought its just `instagram_base_path` + `uri`?

2022-07-19 19:42 UTC, Kahtaf approved these changes
Appreciate all this work! Minor comment but approved otherwise.

2022-07-19 19:42 UTC, Kahtaf commented on src/extractor/instagram/models/accountInformation.ts
> +   * Exists: JSON
My only thought here is that I think we should assume the field exists in both by default, to decrease the verbose comments. If we notice a field exists in one but not the other, let's make a note of it then. What do you think?

2022-07-19 19:42 UTC, Kahtaf commented on src/extractor/instagram/models/profileChanges.ts
> +        console.warn(`Unknown key: ${key} -- value: ${value}`);
Let's use `util/logger.ts` for any console logs in this repo (not including test code). It formats the statement nicely for the browser. And for this specific console log, I'd include the object name too (ProfileChanges).

2022-07-27 14:54 UTC, Kahtaf commented on src/extractor/instagram/json/personalInformationJson.ts
> +      profile_photo: mediaData.uri,
This is what I have seen in sample IG exports, it's a local path. Let's keep it for now, I see that it contains some part of the actual URL. Maybe it can be used to build the actual URL.

```
Export data (local file path):
"uri": "media/other/13167288_176460202750036_1205308000_a_17855760448055185.jpg",

Actual URL of the image:
https://scontent.cdninstagram.com/v/t51.2885-19/13167288_176460202750036_1205308000_a.jpg?stp=dst-jpg_s150x150&_nc_ht=scontent.cdninstagram.com&_nc_cat=104&_nc_ohc=tIluk8STKIoAX9szCCh&edm=APs17CUBAAAA&ccb=7-5&oh=00_AT_CZmob_1wBJRzZAYG8XsDbFDi6lM7l9GDfoU26uaBawQ&oe=62E8E09F&_nc_sid=978cb9
```

2022-07-27 17:22 UTC, Kahtaf approved these changes
I made a few very minor changes but I think this PR is good to merge now 👍

2022-07-27 17:22 UTC, Kahtaf commented on src/extractor/instagram/models/accountInformation.ts
> +   * Exists: JSON
Hope you don't mind me removing these comments for now. I can't think of a reason to track this at the moment, but if we have one, I think it should be in a more programmatic way so that information can be used. When a value doesn't exist in one file format, we should just fill in a blank value so that the schema doesn't change between two file formats.

2022-07-27 17:34 UTC, merged